// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agentlink/agentlink.proto

// Package agentlink is the control-plane <-> agent control channel. The agent
// dials the control plane and holds one long-lived bidirectional stream open;
// the control plane pushes commands down it and the agent answers. This inverts
// the older model where the control plane dialed each agent's HTTP API, so
// agents need no inbound reachability.

package agentlinkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage is anything the agent sends up the stream.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Result
	//	*AgentMessage_Heartbeat
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agentlink_agentlink_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *Result {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // first frame only
}

type AgentMessage_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"` // answer to a Command, correlated by id
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // liveness, on a ticker
}

func (*AgentMessage_Register) isAgentMessage_Body() {}

func (*AgentMessage_Result) isAgentMessage_Body() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Body() {}

// ControlMessage is anything the control plane pushes down the stream.
type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // a VM lifecycle command to execute locally
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_agentlink_agentlink_proto_rawDescGZIP(), []int{1}
}

func (x *ControlMessage) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

// Register identifies the host on stream open. It mirrors the fields the old
// HTTP register carried, minus address: the control plane no longer dials the
// agent, so there is nothing to advertise.
type Register struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // agent-owned stable id (keeps identity across restarts)
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	CpusTotal     int32                  `protobuf:"varint,4,opt,name=cpus_total,json=cpusTotal,proto3" json:"cpus_total,omitempty"`
	MemoryMbTotal int32                  `protobuf:"varint,5,opt,name=memory_mb_total,json=memoryMbTotal,proto3" json:"memory_mb_total,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_proto_agentlink_agentlink_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Register) GetCpusTotal() int32 {
	if x != nil {
		return x.CpusTotal
	}
	return 0
}

func (x *Register) GetMemoryMbTotal() int32 {
	if x != nil {
		return x.MemoryMbTotal
	}
	return 0
}

func (x *Register) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// Command is one VM lifecycle request. payload is the JSON of the existing Go
// type for the op (agent.VMSpec for provision; {"vm_id":...} otherwise), so the
// command schema stays single-sourced in Go rather than duplicated here.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // correlation id, echoed in the matching Result
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`           // provision|start|stop|snapshot|deprovision|status
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON request body for the op
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_agentlink_agentlink_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Result answers a Command. payload is the JSON of agent.VM when the op returns
// one (provision/start/status); error is non-empty when the op failed.
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // matches the Command id
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON agent.VM, or empty
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // non-empty on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_agentlink_agentlink_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Result) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Heartbeat proves liveness over the same stream. The stream itself is the
// primary liveness signal; this keeps the control plane's heartbeat-TTL reaper
// working as a backstop.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentlink_agentlink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agentlink_agentlink_proto_rawDescGZIP(), []int{5}
}

var File_proto_agentlink_agentlink_proto protoreflect.FileDescriptor

const file_proto_agentlink_agentlink_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/agentlink/agentlink.proto\x12\tagentlink\"\xac\x01\n" +
	"\fAgentMessage\x121\n" +
	"\bregister\x18\x01 \x01(\v2\x13.agentlink.RegisterH\x00R\bregister\x12+\n" +
	"\x06result\x18\x02 \x01(\v2\x11.agentlink.ResultH\x00R\x06result\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.agentlink.HeartbeatH\x00R\theartbeatB\x06\n" +
	"\x04body\">\n" +
	"\x0eControlMessage\x12,\n" +
	"\acommand\x18\x01 \x01(\v2\x12.agentlink.CommandR\acommand\"\xb6\x01\n" +
	"\bRegister\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\x1d\n" +
	"\n" +
	"cpus_total\x18\x04 \x01(\x05R\tcpusTotal\x12&\n" +
	"\x0fmemory_mb_total\x18\x05 \x01(\x05R\rmemoryMbTotal\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\"C\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"H\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\v\n" +
	"\tHeartbeat2N\n" +
	"\tAgentLink\x12A\n" +
	"\aConnect\x12\x17.agentlink.AgentMessage\x1a\x19.agentlink.ControlMessage(\x010\x01BBZ@github.com/aarani/craftling-go/internal/agentlink/pb;agentlinkpbb\x06proto3"

var (
	file_proto_agentlink_agentlink_proto_rawDescOnce sync.Once
	file_proto_agentlink_agentlink_proto_rawDescData []byte
)

func file_proto_agentlink_agentlink_proto_rawDescGZIP() []byte {
	file_proto_agentlink_agentlink_proto_rawDescOnce.Do(func() {
		file_proto_agentlink_agentlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentlink_agentlink_proto_rawDesc), len(file_proto_agentlink_agentlink_proto_rawDesc)))
	})
	return file_proto_agentlink_agentlink_proto_rawDescData
}

var file_proto_agentlink_agentlink_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_agentlink_agentlink_proto_goTypes = []any{
	(*AgentMessage)(nil),   // 0: agentlink.AgentMessage
	(*ControlMessage)(nil), // 1: agentlink.ControlMessage
	(*Register)(nil),       // 2: agentlink.Register
	(*Command)(nil),        // 3: agentlink.Command
	(*Result)(nil),         // 4: agentlink.Result
	(*Heartbeat)(nil),      // 5: agentlink.Heartbeat
}
var file_proto_agentlink_agentlink_proto_depIdxs = []int32{
	2, // 0: agentlink.AgentMessage.register:type_name -> agentlink.Register
	4, // 1: agentlink.AgentMessage.result:type_name -> agentlink.Result
	5, // 2: agentlink.AgentMessage.heartbeat:type_name -> agentlink.Heartbeat
	3, // 3: agentlink.ControlMessage.command:type_name -> agentlink.Command
	0, // 4: agentlink.AgentLink.Connect:input_type -> agentlink.AgentMessage
	1, // 5: agentlink.AgentLink.Connect:output_type -> agentlink.ControlMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_agentlink_agentlink_proto_init() }
func file_proto_agentlink_agentlink_proto_init() {
	if File_proto_agentlink_agentlink_proto != nil {
		return
	}
	file_proto_agentlink_agentlink_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentlink_agentlink_proto_rawDesc), len(file_proto_agentlink_agentlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentlink_agentlink_proto_goTypes,
		DependencyIndexes: file_proto_agentlink_agentlink_proto_depIdxs,
		MessageInfos:      file_proto_agentlink_agentlink_proto_msgTypes,
	}.Build()
	File_proto_agentlink_agentlink_proto = out.File
	file_proto_agentlink_agentlink_proto_goTypes = nil
	file_proto_agentlink_agentlink_proto_depIdxs = nil
}
