// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/agentlink/agentlink.proto

// Package agentlink is the control-plane <-> agent control channel. The agent
// dials the control plane and holds one long-lived bidirectional stream open;
// the control plane pushes commands down it and the agent answers. This inverts
// the older model where the control plane dialed each agent's HTTP API, so
// agents need no inbound reachability.

package agentlinkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentLink_Connect_FullMethodName = "/agentlink.AgentLink/Connect"
)

// AgentLinkClient is the client API for AgentLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentLink is served by the control plane and dialed by every agent.
type AgentLinkClient interface {
	// Connect is opened once by the agent and kept open for its lifetime. The
	// agent sends a Register frame first, then Results (answers to Commands) and
	// periodic Heartbeats; the control plane streams Commands back down.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error)
}

type agentLinkClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentLinkClient(cc grpc.ClientConnInterface) AgentLinkClient {
	return &agentLinkClient{cc}
}

func (c *agentLinkClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentLink_ServiceDesc.Streams[0], AgentLink_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ControlMessage]

// AgentLinkServer is the server API for AgentLink service.
// All implementations must embed UnimplementedAgentLinkServer
// for forward compatibility.
//
// AgentLink is served by the control plane and dialed by every agent.
type AgentLinkServer interface {
	// Connect is opened once by the agent and kept open for its lifetime. The
	// agent sends a Register frame first, then Results (answers to Commands) and
	// periodic Heartbeats; the control plane streams Commands back down.
	Connect(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error
	mustEmbedUnimplementedAgentLinkServer()
}

// UnimplementedAgentLinkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentLinkServer struct{}

func (UnimplementedAgentLinkServer) Connect(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentLinkServer) mustEmbedUnimplementedAgentLinkServer() {}
func (UnimplementedAgentLinkServer) testEmbeddedByValue()                   {}

// UnsafeAgentLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentLinkServer will
// result in compilation errors.
type UnsafeAgentLinkServer interface {
	mustEmbedUnimplementedAgentLinkServer()
}

func RegisterAgentLinkServer(s grpc.ServiceRegistrar, srv AgentLinkServer) {
	// If the following call panics, it indicates UnimplementedAgentLinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentLink_ServiceDesc, srv)
}

func _AgentLink_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentLinkServer).Connect(&grpc.GenericServerStream[AgentMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentLink_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ControlMessage]

// AgentLink_ServiceDesc is the grpc.ServiceDesc for AgentLink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentLink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentlink.AgentLink",
	HandlerType: (*AgentLinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentLink_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agentlink/agentlink.proto",
}
