//go:build linux

package main

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/aarani/craftling-go/internal/runspec"
	"golang.org/x/sys/unix"
)

// resolvConfPath is the guest resolver file the workload reads. The image
// rootfs is read-only, so writeResolvConf stages the real file on the /run
// tmpfs and bind-mounts it here.
const resolvConfPath = "/etc/resolv.conf"

// writeResolvConf points the guest's /etc/resolv.conf at nameservers. The
// rootfs is a read-only squashfs and the image ships no usable resolv.conf, so
// nothing resolves names over the NAT dataplane until we populate it: we write
// the file onto the /run tmpfs (mounted by setupInit) and bind-mount it over
// the rootfs path, which the kernel allows even though the rootfs is read-only.
// A no-op when no nameservers are configured (MMDS-only hosts).
func writeResolvConf(nameservers []string) error {
	if len(nameservers) == 0 {
		return nil
	}
	var b strings.Builder
	b.WriteString("# generated by craftling init\n")
	for _, ns := range nameservers {
		if ns = strings.TrimSpace(ns); ns != "" {
			fmt.Fprintf(&b, "nameserver %s\n", ns)
		}
	}

	staged := filepath.Join(persistScratch, "..", "resolv.conf") // /run/craftling/resolv.conf
	if err := os.MkdirAll(filepath.Dir(staged), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(staged), err)
	}
	if err := os.WriteFile(staged, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", staged, err)
	}
	if err := syscall.Mount(staged, resolvConfPath, "", syscall.MS_BIND, ""); err != nil {
		return fmt.Errorf("bind %s over %s: %w", staged, resolvConfPath, err)
	}
	return nil
}

// setupNetwork brings the guest's MMDS interface up with its static
// link-local address. The kernel may already have done this from the
// ip= boot arg (CONFIG_IP_PNP), but that config option isn't universal
// across Firecracker kernels, so init configures the interface itself
// too. It is idempotent — re-assigning the same address the kernel
// already set is harmless — and best-effort: the caller logs a warning
// rather than aborting, because the MMDS fetch that follows will surface
// any real connectivity failure with a clearer error.
func setupNetwork() error {
	sock, err := unix.Socket(unix.AF_INET, unix.SOCK_DGRAM|unix.SOCK_CLOEXEC, 0)
	if err != nil {
		return fmt.Errorf("socket: %w", err)
	}
	defer func() { _ = unix.Close(sock) }()

	if err := setIfaceAddr(sock, runspec.MMDSInterface, runspec.GuestIPv4, runspec.GuestNetmask); err != nil {
		return err
	}
	if err := setIfaceUp(sock, runspec.MMDSInterface); err != nil {
		return err
	}
	return nil
}

// applyNetConfig applies the per-VM networking the host's NAT dataplane
// expects, on top of the link-local MMDS address already configured: it adds
// the private VM address as a secondary address, installs a permanent neighbor
// for the virtual gateway (which no host interface owns, so an ARP would go
// unanswered), and adds the default route through it. Order matters — the
// neighbor is installed before the route so the gateway resolves immediately.
func applyNetConfig(nc *runspec.NetConfig) error {
	ifaceName := nc.Interface
	if ifaceName == "" {
		ifaceName = runspec.MMDSInterface
	}
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return fmt.Errorf("lookup %s: %w", ifaceName, err)
	}

	ip := net.ParseIP(nc.Address)
	if ip == nil {
		return fmt.Errorf("invalid VM address %q", nc.Address)
	}
	gw := net.ParseIP(nc.Gateway)
	if gw == nil {
		return fmt.Errorf("invalid gateway %q", nc.Gateway)
	}
	mac, err := net.ParseMAC(nc.GatewayMAC)
	if err != nil {
		return fmt.Errorf("invalid gateway MAC %q: %w", nc.GatewayMAC, err)
	}

	if err := addInterfaceAddr(iface.Index, ip, nc.PrefixLen); err != nil {
		return fmt.Errorf("add address %s/%d: %w", nc.Address, nc.PrefixLen, err)
	}
	if err := addNeighbor(iface.Index, gw, mac); err != nil {
		return fmt.Errorf("add gateway neighbor %s: %w", nc.Gateway, err)
	}
	if err := addDefaultRoute(iface.Index, gw); err != nil {
		return fmt.Errorf("add default route via %s: %w", nc.Gateway, err)
	}
	return nil
}

// setIfaceAddr assigns an IPv4 address and netmask to iface via the
// classic SIOCSIFADDR / SIOCSIFNETMASK ioctls.
func setIfaceAddr(sock int, iface, addr, mask string) error {
	if err := ioctlSetSockaddr(sock, unix.SIOCSIFADDR, iface, addr); err != nil {
		return fmt.Errorf("set addr %s on %s: %w", addr, iface, err)
	}
	if err := ioctlSetSockaddr(sock, unix.SIOCSIFNETMASK, iface, mask); err != nil {
		return fmt.Errorf("set netmask %s on %s: %w", mask, iface, err)
	}
	return nil
}

// setIfaceUp sets IFF_UP|IFF_RUNNING on iface.
func setIfaceUp(sock int, iface string) error {
	ifr, err := unix.NewIfreq(iface)
	if err != nil {
		return fmt.Errorf("ifreq %q: %w", iface, err)
	}
	if err := unix.IoctlIfreq(sock, unix.SIOCGIFFLAGS, ifr); err != nil {
		return fmt.Errorf("SIOCGIFFLAGS: %w", err)
	}
	ifr.SetUint16(ifr.Uint16() | unix.IFF_UP | unix.IFF_RUNNING)
	if err := unix.IoctlIfreq(sock, unix.SIOCSIFFLAGS, ifr); err != nil {
		return fmt.Errorf("SIOCSIFFLAGS: %w", err)
	}
	return nil
}

// ioctlSetSockaddr issues an ifreq ioctl whose payload is a sockaddr_in
// carrying dotted-quad. x/sys/unix's Ifreq exposes SetInet4Addr, which
// packs exactly the AF_INET sockaddr the SIOCSIF{ADDR,NETMASK} ioctls
// expect.
func ioctlSetSockaddr(sock int, req uint, iface, dottedQuad string) error {
	ifr, err := unix.NewIfreq(iface)
	if err != nil {
		return fmt.Errorf("ifreq %q: %w", iface, err)
	}
	ip := net.ParseIP(dottedQuad).To4()
	if ip == nil {
		return fmt.Errorf("invalid IPv4 %q", dottedQuad)
	}
	if err := ifr.SetInet4Addr(ip); err != nil {
		return fmt.Errorf("set inet4 addr: %w", err)
	}
	return unix.IoctlIfreq(sock, req, ifr)
}
